nexus-archive/website/src/Contract/Entity/LeaderboardTypes.php
<?php

declare(strict_types=1);

namespace App\Contract\Entity;

// TODO convert into native enum when PHP 8.1 is available
final class LeaderboardTypes
{
    public const BREATH = 'breath';
    public const CAREER = 'career';

    public static function cases(): array
    {
        return [
            self::BREATH,
            self::CAREER,
        ];
    }
}

nexus-archive/website/src/Contract/Entity/Nexus/Leaderboard/EntryInterface.php
<?php

declare(strict_types=1);

namespace App\Contract\Entity\Nexus\Leaderboard;

interface EntryInterface
{
    public function getCharacterName(): ?string;

    public function setCharacterName(string $characterName): void;

    public function getScore(): ?int;

    public function setScore(int $value): void;
}

nexus-archive/website/src/Contract/Entity/Nexus/Leaderboard/EntryListInterface.php
<?php

declare(strict_types=1);

namespace App\Contract\Entity\Nexus\Leaderboard;

use ArrayAccess;
use Countable;
use InvalidArgumentException;
use Iterator;

/**
 * Sorted collection of leaderboard entries.
 */
interface EntryListInterface extends Iterator, ArrayAccess, Countable
{
    /** Iterator interface: Return the current element */
    public function current(): ?EntryInterface;

    /** Iterator interface: Return the key of the current element */
    public function key(): ?int;

    /** Iterator interface: Move forward to next element */
    public function next(): void;

    /** Iterator interface: Rewind the Iterator to the first element */
    public function rewind(): void;

    /** Iterator interface: Checks if current position is valid */
    public function valid(): bool;

    /** ArrayAccess interface: Whether an offset exists */
    public function offsetExists(mixed $offset): bool;

    /** ArrayAccess interface: Offset to retrieve */
    public function offsetGet(mixed $offset): ?EntryInterface;

    /**
     * ArrayAccess interface: Assign a value to the specified offset
     *
     * @throws InvalidArgumentException when $offset ins not an integer
     * @throws InvalidArgumentException when $value is not an instance of EntryInterface
     */
    public function offsetSet(mixed $offset, mixed $value): void;

    /** ArrayAccess interface: Unset an offset */
    public function offsetUnset(mixed $offset): void;

    /** Countable interface: Count elements of an object */
    public function count(): int;
}

nexus-archive/website/src/Doctrine/Entity/Nexus/Leaderboard.php
<?php

declare(strict_types=1);

namespace App\Doctrine\Entity\Nexus;

use App\Contract\Doctrine\Entity\DatedEntityInterface;
use App\Contract\Doctrine\Entity\GamePeriodReferenceInterface;
use App\Contract\Doctrine\Entity\UuidPrimaryKeyInterface;
use App\Contract\Entity\Nexus\GamePeriodInterface;
use App\Doctrine\Entity\DatedEntityTrait;
use App\Doctrine\Entity\UuidPrimaryKeyTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[
    ORM\Entity,
    ORM\Table(name: 'nexus_leaderboard'),
    ORM\UniqueConstraint(name: 'nexus_leaderboard_uniq', fields: ['category', 'gamePeriod']),
    ORM\Index(fields: ['category'], name: 'nexus_leaderboard_category_idx'),
    ORM\Index(fields: ['gamePeriod'], name: 'nexus_leaderboard_game_period_idx'),
]
class Leaderboard implements UuidPrimaryKeyInterface, GamePeriodReferenceInterface, DatedEntityInterface
{
    use UuidPrimaryKeyTrait;
    use DatedEntityTrait;

    #[
        ORM\ManyToOne(targetEntity: LeaderboardCategory::class),
        ORM\JoinColumn(name: 'category_id', referencedColumnName: 'id', nullable: false),
    ]
    private ?LeaderboardCategory $category = null;

    #[
        ORM\ManyToOne(targetEntity: GamePeriod::class),
        ORM\JoinColumn(name: 'game_period_id', referencedColumnName: 'id', nullable: false),
    ]
    private ?GamePeriodInterface $gamePeriod = null;

    #[
        ORM\OneToMany(mappedBy: 'leaderboard', targetEntity: LeaderboardEntry::class),
        ORM\OrderBy(value: ['position' => 'ASC']),
    ]
    private Collection $entries;

    public function __construct()
    {
        $this->generateId();
        $this->entries = new ArrayCollection();
    }

    public function getCategory(): ?LeaderboardCategory
    {
        return $this->category;
    }

    public function setCategory(LeaderboardCategory $category): void
    {
        $this->category = $category;
    }

    public function getGamePeriod(): ?GamePeriodInterface
    {
        return $this->gamePeriod;
    }

    public function setGamePeriod(GamePeriodInterface $gamePeriod): void
    {
        $this->gamePeriod = $gamePeriod;
    }

    public function getEntries(): Collection
    {
        return $this->entries;
    }
}

nexus-archive/website/src/Controller/LeaderboardController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Contract\Config\AppRoutes;
use App\Service\Repository\Nexus\GamePeriodRepository;
use App\Service\Repository\Nexus\LeaderboardRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Twig\Environment;

use function array_key_exists;
use function intval;
use function sprintf;

final class LeaderboardController
{
    public function __construct(
        private Environment $twigEnvironment,
        private GamePeriodRepository $gamePeriodRepository,
        private LeaderboardRepository $leaderboardRepository,
    ) {
    }

    #[Route(path: '/leaderboards', name: AppRoutes::LEADERBOARDS, methods: [Request::METHOD_GET])]
    public function index(
        Request $request
    ): Response {
        $gamePeriods = $this->gamePeriodRepository->findAll();

        $defaultGamePeriodId = null;
        $optionsGamePeriods = [];
        foreach ($gamePeriods as $gamePeriod) {
            $id = $gamePeriod->getId();
            $optionsGamePeriods[$id] = $gamePeriod;
            if ($gamePeriod->isCurrent()) {
                $defaultGamePeriodId = $id;
            }
        }

        $selectedGamePeriodStr = $request->get(key: 'gamePeriod');
        if (null !== $selectedGamePeriodStr) {
            $selectedGamePeriodId = intval(value: $selectedGamePeriodStr);
            if (false === array_key_exists(key: $selectedGamePeriodId, array: $optionsGamePeriods)) {
                throw new NotFoundHttpException(
                    message: sprintf('Invalid ID of game period: %d', $selectedGamePeriodId)
                );
            }
        } else {
            $selectedGamePeriodId = $defaultGamePeriodId;
        }

        $selectedGamePeriod = $optionsGamePeriods[$selectedGamePeriodId];
        $leaderboards = $this->leaderboardRepository->findByGamePeriod(gamePeriod: $selectedGamePeriod);

        $context = [
            'optionsGamePeriods' => $optionsGamePeriods,
            'selectedGamePeriodId' => $selectedGamePeriodId,
            'leaderboards' => $leaderboards,
        ];
        $responseBody = $this->twigEnvironment->render(name: 'leaderboards/index.html.twig', context: $context);

        return new Response(content: $responseBody);
    }

}

nexus-archive/website/templates/leaderboards/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Leaderboards - Nexus Archive{% endblock %}

{% block body %}
    <h1>Leaderboards</h1>

    <section>
        <form action="" method="get">
            <label>
                Game period:
                <select name="gamePeriod">
                    {% for id, item in optionsGamePeriods %}
                        <option value="{{ id }}"
                                {% if id == selectedGamePeriodId %}selected{% endif %}>{{ item.name }}</option>
                    {% endfor %}
                </select>
            </label>
            <button type="submit">Switch</button>
        </form>
    </section>

    <section class="leaderboard-grid">
        {% for leaderboard in leaderboards %}
            <article>
                <table>
                    <caption>{{ leaderboard.category.name }} ({{ leaderboard.category.type|capitalize }})</caption>
                    <thead>
                    <tr>
                        <th>Position</th>
                        <th>Character</th>
                        <th>{{ leaderboard.category.scoreLabel }}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for entry in leaderboard.entries %}
                        <tr>
                            <td>{{ entry.position }}</td>
                            <td>{{ entry.characterName }}</td>
                            <td>{{ entry.score }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </article>
        {% else %}
            <article class="error">No leaderboards found for selected period.</article>
        {% endfor %}
    </section>
{% endblock %}